### PR TITLE
feat: add social icons & google analytics 

### PR DESCRIPTION
**Pull request by vaultec81**

### CODE REVIEW

**Review by kanej — APPROVED** [review]
I have pulled the branch locally, the social icons look good, so does the ga integration.

**Comment by kanej** [comment]
@vaultec81 can you rebase and merge in your changes?

**Review by AquiGorka — COMMENTED** [review]
Let's make sure we are not adding icons that are not needed. I see this PR adds `5000+` files and I don't want the repo to become unmanageable.

**Comment by vaultec81** [comment]
@AquiGorka I have removed all the extra icons in one of the other commits, however git still shows 5000+ files. Not sure as to why this is the case.

**Pull request merged**
